#!/bin/bash
TITLE=${1}
POSTDIR=./_posts

if [ ! -n "${TITLE}" ]; then
  echo "USAGE: mkpost title-of-post"
  exit 1
fi

if [ ! -n "${EDITOR}" ]; then
  if [ -n "`which vim`" ]; then
    EDITOR=vim
  elif [ -n "`which nano`" ]; then
    EDITOR=nano
  elif [ -n "`which emacs`" ]; then
    EDITOR=emacs
  else
    echo "Couldn't find an editor. Tried vim, nano, & emacs. Try \`export EDITOR=your-favorite-editor\` "
  fi
fi

FILE=`date "+%Y-%m-%d"`-${TITLE}.md

if [ ! -e "${POSTDIR}/${FILE}" ]
then
  mkdir -p ${POSTDIR}
  cat - > ${POSTDIR}/${FILE} << EOF
---
layout: article
title: `echo ${TITLE} | sed 's/-/ /g'`
categories: !!UPDATED ME!!
updated_at: `date +'%Y-%m-%d'`
---

    You just created ${POSTDIR}/${FILE}!

    Notice the UPDATED ME in the categories above.
    Please change that to be a category.

    Your article starts after the last -- above.
    

    Remember
        
        Code blocks are indented by 4 spaces

    Paragraphs have two spaces between lines.
    Sentances have one.

      * lists can be bullet
      * like this

    or

      1. can be numbered
      2. like this

    Large Header
    ====

    Small Header
    ----

    >  block quotes have
    >  a carret and two spaces
    >
    >    and can contain code
    >
    >  * bullets
    >
    >  1. etc

EOF
fi

$EDITOR ${POSTDIR}/${FILE}
